package star.power;

import java.awt.Font;
import static java.lang.Thread.sleep;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.ItemEvent;
import java.awt.print.PrinterException;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.util.Random;
import javax.swing.JTextArea;
import java.util.Vector.*;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
/**
 * @author AslamRathore
 */
public final class Tools extends javax.swing.JFrame {
     /**
     * Creates new form Tools
     */
      DefaultTableModel model;
      
      String SubTotal;
      String CGST;
      String SGST;
      String GrandTotal;
      
      final JList list;
      String item="";
      Boolean editable=false;
      
      int gst_area_set;
      
      //deleted decimal ager zero value only
        DecimalFormat df = new DecimalFormat("###.##");
      

      
      public Tools() {
        initComponents();
        showTime();
        
       //  MyTable.setAutoResizeMode(MyTable.AUTO_RESIZE_OFF);
        TableColumn col = MyTable.getColumnModel().getColumn(0);
        col.setPreferredWidth(200);
        TableColumn col1 = MyTable.getColumnModel().getColumn(1);
        col1.setPreferredWidth(100);
        
        ItemComboBox.setEditable(false);
        list = new JList(new DefaultListModel());
        
      }
      
      
    
   void showTime() {
       
       Thread showTime;
          showTime = new Thread() {
              
              @Override
              public void run() {
                  
                  try {
                      
                      for(;;) {
                          Date cal1 = new Date();
                          SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
                          SimpleDateFormat sdf1 = new SimpleDateFormat("MM-dd-yyyy");
                          TTextField.setText(sdf.format(cal1));
                          DTextField.setText(sdf1.format(cal1));
                          sleep(1000);
                      }
                  } catch (InterruptedException ex) {
                      Logger.getLogger(Tools.class.getName()).log(Level.SEVERE, null, ex);
                  }
              }
          };
       showTime.start();
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CNTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CMTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ItemComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        MRPTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ItemPurcsdTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        discountTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        SPTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        QTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        DTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        ATextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        AddButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        MyTable = new javax.swing.JTable();
        GSTLabel = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        CGSTTextField3 = new javax.swing.JTextField();
        SGSTTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        IGSTTextField2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        TButton = new javax.swing.JButton();
        PButton = new javax.swing.JButton();
        GRButton = new javax.swing.JButton();
        DATextField = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        STTextField = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        GRTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("CUSTOMER NAME");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("CUSTOMER MOBILE NO.");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("ITEMS");

        ItemComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DEMOLITION MACHINE          ", "VIBRATOR DRILL                ", "14\" Cut off Machine          ", "Surie Mirrex Pad             ", "MARBLE CUTTER MACHINE    ", "ANGLE GRINDER MACHINE    ", "FEILD COIL                     ", "DRILL MACHINE                ", "HEAT GUN                       ", "ROTARY HAMMER MACHINE      ", "BLADES                    ", "CARBON BRUSH              " }));
        ItemComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ItemComboBoxItemStateChanged(evt);
            }
        });
        ItemComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemComboBoxActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("MRP");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("INVOICE NO.");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("ITEM PURCSD");

        ItemPurcsdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemPurcsdTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("DISCOUNT %");

        discountTextField.setText("00");
        discountTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountTextFieldActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("RATE");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("QUANTITY");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("DATE");

        DTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DTextFieldActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("TIME");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("AMOUNT");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("ADD ITEMS");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("CLEAR CART");

        AddButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        AddButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/star/power/png/AddCart.png"))); // NOI18N
        AddButton.setText("ADD");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        ClearButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ClearButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/star/power/png/Clear.png"))); // NOI18N
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        MyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ITEM", "MRP", "QTY", "RATE", "AMOUNT"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        MyTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MyTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(MyTable);

        GSTLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        GSTLabel.setText("GST %");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "18", "0", "12", "5", "28" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("CGST AMOUNT");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("SGST AMOUNT");

        CGSTTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CGSTTextField3ActionPerformed(evt);
            }
        });

        SGSTTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SGSTTextFieldActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("IGST AMOUNT");

        IGSTTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IGSTTextField2ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("CALCULATE TOTAL");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("GENERATE RECEIPT");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("PRINT RECEIPT");

        TButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TButton.setText("TOTAL");
        TButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TButtonActionPerformed(evt);
            }
        });

        PButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        PButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/star/power/png/Print.png"))); // NOI18N
        PButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PButtonActionPerformed(evt);
            }
        });

        GRButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        GRButton.setText("RECEIPT");
        GRButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GRButtonMouseClicked(evt);
            }
        });
        GRButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GRButtonActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("DISCOUNT AMOUNT");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setText("SUB TOTAL");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setText("GRAND TOTAL");

        area.setColumns(20);
        area.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        area.setBorder(null);
        area.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                areaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(area);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel21.setText("  Star Power tools and Chemical's ");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton1.setText("ITEM SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jCheckBox1.setText("ITEMS ADD");
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CNTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CMTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ItemComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MRPTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(discountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(QTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24)
                                        .addComponent(SPTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ATextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(AddButton)
                                                .addGap(18, 18, 18)
                                                .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(55, 55, 55)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(25, 25, 25)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(188, 188, 188))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(ItemPurcsdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel6))
                                                .addGap(43, 43, 43)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(DTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(28, 28, 28)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(TTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 841, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(GSTLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(29, 29, 29)
                                    .addComponent(jLabel18))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(31, 31, 31)
                                    .addComponent(jLabel15)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel19)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CGSTTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SGSTTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IGSTTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(29, 29, 29)
                                    .addComponent(STTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(1, 1, 1))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel22)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(DATextField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(GRTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(GRButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(TButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(67, 67, 67)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel21)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CNTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CMTextField)
                        .addComponent(jTextField1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ItemPurcsdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ItemComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MRPTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(discountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(QTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ATextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AddButton)
                        .addComponent(SPTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ClearButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GSTLabel)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(CGSTTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DATextField)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23)
                        .addComponent(jLabel19)
                        .addComponent(SGSTTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCheckBox1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(STTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(GRButton))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(IGSTTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(GRTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PButton)
                    .addComponent(jButton1))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void SGSTTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SGSTTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SGSTTextFieldActionPerformed


    private void ItemComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemComboBoxActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_ItemComboBoxActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed

       double a = Double.parseDouble(MRPTextField.getText());

      int  b = Integer.parseInt(QTextField.getText());
      double   amt = a * b;
      double   discount = amt/100 * Double.parseDouble(discountTextField.getText());
      double   amount = amt - discount;
      
      
    
      System.out.println(df.format(amt));
      SPTextField.setText("" + df.format(amt));
      
     System.out.println(df.format(amount));
     ATextField.setText("" + df.format(amount));
        
    
       
         model = (DefaultTableModel) MyTable.getModel();
        model.addRow(new Object[]{ItemComboBox.getSelectedItem(),
            MRPTextField.getText(), QTextField.getText(), SPTextField.getText(),
            ATextField.getText()});
     
             int col = model.getRowCount();
             ItemPurcsdTextField.setText(""+col);
             
       //       MRPTextField.setText("");
          //    SPTextField.setText("");
          //    QTextField.setText("");
        //      ATextField.setText("");
       
    }//GEN-LAST:event_AddButtonActionPerformed

    private void TButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TButtonActionPerformed
        // TODO add your handling code here:
        double z = 0;
        for (int i = 0; i < MyTable.getRowCount(); i++) {
            z += Double.parseDouble(MyTable.getValueAt(i, 4).toString());
        }
        
         System.out.println(df.format(z));
        STTextField.setText(df.format(z) + " ");
        
        double y = 0;
        for(int j=0; j<MyTable.getRowCount(); j++) {
            y+= Double.parseDouble(MyTable.getValueAt(j, 3).toString());
        }
        
       double zy =y-z;
       double round = Math.round(zy *100)/100.0;
       DATextField.setText(""+round);
       
     
        String cb = jComboBox1.getSelectedItem().toString();
          double bc = Double.parseDouble(cb);
            
          int value = (int)bc;
          gst_area_set = value/2;
        
          String st = STTextField.getText();
          double ts = Double.parseDouble(st);
          
         double gst = (ts*bc)/100;
         
        double  netamount = ts+gst;
        
        double aslam = gst/2;
        
       double gst1 = Math.round(aslam *100)/100.0;
       String rathore = Double.toString(gst1);
       
      CGSTTextField3.setText(rathore);
      SGSTTextField.setText(rathore);
  
      
       double GrandTotal = Math.round(netamount *100)/100.0;
    //  int j = (int)Math.round(z);
              System.out.println(df.format(GrandTotal));

      GRTextField.setText(""+df.format(GrandTotal));
      
       
      

    }//GEN-LAST:event_TButtonActionPerformed

    private void MyTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyTableMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_MyTableMouseClicked

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        // TODO add your handling code here:
        MRPTextField.setText("");
        SPTextField.setText("");
        QTextField.setText("");
        ATextField.setText("");
        STTextField.setText("");
        discountTextField.setText("00");
        ItemPurcsdTextField.setText("");
        CGSTTextField3.setText("");
        SGSTTextField.setText("");
        DATextField.setText("");
        GRTextField.setText("");
        area.setText("");
        jTextField1.setText("");
        CNTextField.setText("");
        CMTextField.setText("");

        DefaultTableModel model = (DefaultTableModel) MyTable.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void DTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DTextFieldActionPerformed

    private void discountTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountTextFieldActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_discountTextFieldActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void IGSTTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IGSTTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IGSTTextField2ActionPerformed

    private void ItemPurcsdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemPurcsdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemPurcsdTextFieldActionPerformed

    private void GRButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GRButtonActionPerformed
   // area.setLineWrap(true);
   // area.setWrapStyleWord(true);
    
        Random ran = new Random();
        int n=ran.nextInt(10000);
        String val=String.valueOf(n);
        jTextField1.setText(val);   
  
   

        
  try {
     SubTotal = STTextField.getText();
    CGST = CGSTTextField3.getText();
      SGST = SGSTTextField.getText();
     GrandTotal = GRTextField.getText();

      
     area.setText("\t\t       Bill Receipt\n");
       area.setText(area.getText()+"---------------------------------------------------------\n");
       area.setText(area.getText()+"Star Power tools and Chemical's"+ "\t\tDate "+ DTextField.getText()+"\n");
       area.setText(area.getText()+"#66/1, 1st Floor Opp Jigani Weight"+ "\tTime "+ TTextField.getText()+"\n");
       area.setText(area.getText()+"Brige Jigani Double Road,"+ "\t\tInvoice No. "+ jTextField1.getText()+"\n");
       area.setText(area.getText()+"Bangalore-560105, Karnataka\n");
       area.setText(area.getText()+"Mob : 6362001534, 9900308104\n");
       area.setText(area.getText()+"E-Mail : Sahilmails60@gmail.com\n");
       area.setText(area.getText()+"---------------------------------------------------------\n");
       area.setText(area.getText()+"Buyer : "+CNTextField.getText()+"\n");
       area.setText(area.getText()+"Mob   : "+CMTextField.getText()+"\n");
       area.setText(area.getText()+"---------------------------------------------------------\n");
       
       
       area.setText(area.getText()+ model.getColumnName(0)+"\t\t\t\t"+model.getColumnName(1)+"\t"+model.getColumnName(2)+"\t"+model.getColumnName(4)+ "\n\n");
        
       area.setText(area.getText()+ model.getValueAt(0, 0)+"\t"+model.getValueAt(0, 1)+"\t"+model.getValueAt(0, 2)+"\t"+model.getValueAt(0, 4)+"\n");
       area.setText(area.getText()+ model.getValueAt(1, 0)+"\t"+model.getValueAt(1, 1)+"\t"+model.getValueAt(1, 2)+"\t"+model.getValueAt(1, 4)+"\n");
       area.setText(area.getText()+ model.getValueAt(2, 0)+"\t"+model.getValueAt(2, 1)+"\t"+model.getValueAt(2, 2)+"\t"+model.getValueAt(2, 4)+"\n");
       area.setText(area.getText()+ model.getValueAt(3, 0)+"\t"+model.getValueAt(3, 1)+"\t"+model.getValueAt(3, 2)+"\t"+model.getValueAt(3, 4)+"\n");
       area.setText(area.getText()+ model.getValueAt(4, 0)+"\t"+model.getValueAt(4, 1)+"\t"+model.getValueAt(4, 2)+"\t"+model.getValueAt(4, 4)+"\n");
       area.setText(area.getText()+ model.getValueAt(5, 0)+"\t"+model.getValueAt(5, 1)+"\t"+model.getValueAt(5, 2)+"\t"+model.getValueAt(5, 4)+"\n");
       area.setText(area.getText()+ model.getValueAt(6, 0)+"\t"+model.getValueAt(6, 1)+"\t"+model.getValueAt(6, 2)+"\t"+model.getValueAt(6, 4)+"\n");
       area.setText(area.getText()+ model.getValueAt(7, 0)+"\t"+model.getValueAt(7, 1)+"\t"+model.getValueAt(7, 2)+"\t"+model.getValueAt(7, 4)+"\n");
       area.setText(area.getText()+ model.getValueAt(8, 0)+"\t"+model.getValueAt(8, 1)+"\t"+model.getValueAt(8, 2)+"\t"+model.getValueAt(8, 4)+"\n");
       area.setText(area.getText()+ model.getValueAt(9, 0)+"\t"+model.getValueAt(9, 1)+"\t"+model.getValueAt(9, 2)+"\t"+model.getValueAt(9, 4)+"\n");
       area.setText(area.getText()+ model.getValueAt(10, 0)+"\t"+model.getValueAt(10, 1)+"\t"+model.getValueAt(10, 2)+"\t"+model.getValueAt(10, 4)+"\n");
     //  area.setText(area.getText()+ model.getValueAt(11, 0)+"\t"+model.getValueAt(11, 1)+"\t"+model.getValueAt(11, 2)+"\t"+model.getValueAt(11, 4)+"\n");
    //   area.setText(area.getText()+ model.getValueAt(12, 0)+"\t"+model.getValueAt(12, 1)+"\t"+model.getValueAt(12, 2)+"\t"+model.getValueAt(12, 4)+"\n");
      
  }catch(Exception e) {
    //  JOptionPane.showMessageDialog(rootPane, e);
  }
  
 area.setText(area.getText()+"\n\n\n---------------------------------------------------------\n");
  
      area.setText(area.getText()+"Total Item : "+ ItemPurcsdTextField.getText()+"\t\t\tSub Total   :   "+STTextField.getText()+"\n");
      area.setText(area.getText()+"\t\t\t\tCGST   "+gst_area_set+"%   :   "+CGSTTextField3.getText()+"\n");
      area.setText(area.getText()+"\t\t\t\tSGST   "+gst_area_set+"%   :   "+CGSTTextField3.getText()+"\n");

      area.setText(area.getText()+"Authorised Signatory\t\tGrand Total :   "+GRTextField.getText()+"\n");
      area.setText(area.getText()+"---------------------------------------------------------\n");
      area.setText(area.getText()+"\t     This is a Computer Generated Invoice");
   
   /* try {
             FileWriter writer = new FileWriter("G:\\PowerTools\\Rathore.txt");
             try (BufferedWriter w = new BufferedWriter(writer)) {
                 area.write(w);
             }
             area.requestFocus();
     }
     catch (Exception e) {
         JOptionPane.showMessageDialog(null, e);
    }*/
   
   
     
    }//GEN-LAST:event_GRButtonActionPerformed

    
    private void areaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_areaMouseClicked
        // TODO add your handling code here:
     
        
    }//GEN-LAST:event_areaMouseClicked

    private void GRButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GRButtonMouseClicked
        // TODO add your handling code here:
     
      //  Graphics g;  g = area.getGraphics();
       //  g.drawLine(0, 27, 355, 27);
        
         
    }//GEN-LAST:event_GRButtonMouseClicked

    private void PButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PButtonActionPerformed
        // TODO add your handling code here:
          try {
            area.print();
        } catch (PrinterException ex) {
            Logger.getLogger(Tools.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PButtonActionPerformed

    private void ItemComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ItemComboBoxItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange()==ItemEvent.SELECTED) {
            ((DefaultListModel)list.getModel()).addElement(ItemComboBox.getSelectedItem());
            item=ItemComboBox.getSelectedItem().toString();
        }
    }//GEN-LAST:event_ItemComboBoxItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ItemComboBox.insertItemAt(item, 0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1ItemStateChanged
        // TODO add your handling code here:
        if(jCheckBox1.isSelected()) {
            editable=true;
        }else {
            editable=false;
        }
        ItemComboBox.setEditable(editable);
    }//GEN-LAST:event_jCheckBox1ItemStateChanged

    private void CGSTTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CGSTTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CGSTTextField3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tools.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tools.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tools.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tools.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Tools().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ATextField;
    private javax.swing.JButton AddButton;
    private javax.swing.JTextField CGSTTextField3;
    private javax.swing.JTextField CMTextField;
    private javax.swing.JTextField CNTextField;
    private javax.swing.JButton ClearButton;
    private javax.swing.JTextField DATextField;
    private javax.swing.JTextField DTextField;
    private javax.swing.JButton GRButton;
    private javax.swing.JTextField GRTextField;
    private javax.swing.JLabel GSTLabel;
    private javax.swing.JTextField IGSTTextField2;
    private javax.swing.JComboBox<String> ItemComboBox;
    private javax.swing.JTextField ItemPurcsdTextField;
    private javax.swing.JTextField MRPTextField;
    private javax.swing.JTable MyTable;
    private javax.swing.JButton PButton;
    private javax.swing.JTextField QTextField;
    private javax.swing.JTextField SGSTTextField;
    private javax.swing.JTextField SPTextField;
    private javax.swing.JTextField STTextField;
    private javax.swing.JButton TButton;
    private javax.swing.JTextField TTextField;
    private javax.swing.JTextArea area;
    private javax.swing.JTextField discountTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
